---
- name: Prepare comunity operator directory
  block:
    - name: "Check if community operators directory exists"
      stat:
        path: "{{ catalog_repo_dir }}"
      register: operator_dir

    - name: "Git clone community operators, since it doesn't exists"
      git:
        repo: "https://github.com/operator-framework/community-operators.git"
        dest: "{{ catalog_repo_dir }}"
        version: master
        force: true
      when: not (operator_dir.stat.isdir is defined and operator_dir.stat.isdir)
  tags:
    - catalog_build

# #future feature
# - name: "Quay login"
#   shell: "docker login -u=\"{{ quay_namespace }}+test\" -p={{ quay_token }} quay.io"
#   no_log: True

- name: "Build catalog image from '{{ catalog_repo_dir }}/{{ catalog_dockerfile }}'"
  docker_image:
    name: "{{ catalog_image_registry }}/{{ catalog_image_namespace }}/{{ catalog_image_name }}"
    build:
      pull: yes
      path: "{{ catalog_repo_dir }}"
      dockerfile: "{{ catalog_repo_dir }}/{{ catalog_dockerfile }}"
      args:
        PERMISSIVE_LOAD: false
    tag: "{{ catalog_image_tag }}"
    push: yes
    source: build
  tags:
    - catalog_build

- name: "Delete previous catalog deployment (it may fail if not exists)"
  shell: "{{ oc_bin_path }} delete deployment {{ catalog_source_name }} -n {{ catalog_source_namespace }}"
  ignore_errors: yes
  tags:
    - catalog_build

#- name: "Create '{{ catalog_source_namespace }}' namespace (it may fail, if already exists)"
#  shell: "{{ oc_bin_path }} create namespace {{ catalog_source_namespace }}"
#  ignore_errors: yes
#  tags:
#    - catalog_build

- name: "Copy namespace file"
  template:
    src: "namespace.yml.js2"
    dest: "/tmp/namespace.yml"

- name: "Create the namespace"
  shell: "{{ oc_bin_path }} apply -f /tmp/namespace.yml"

- name: "Deploy catalog image as deployment '{{ catalog_source_name }}' in '{{ catalog_source_namespace }}' namespace"
  shell: "{{ oc_bin_path }} create deployment {{ catalog_source_name }} --image={{ catalog_image_registry }}/{{ catalog_image_namespace }}/{{ catalog_image_name }}:{{ catalog_image_tag }} -n={{ catalog_source_namespace }}"
  tags:
    - catalog_build