---
- name: Prepare comunity operator directory
  block:
    - name: "Check if community operators directory exists"
      stat:
        path: "{{ catalog_repo_dir }}"
      register: operator_dir

    - name: "Git clone community operators, since it doesn't exists"
      git:
        repo: "https://github.com/operator-framework/community-operators.git"
        dest: "{{ catalog_repo_dir }}"
        version: master
        force: true
      when: not (operator_dir.stat.isdir is defined and operator_dir.stat.isdir)
  tags:
    - catalog_build

- name: "Build catalgue image from '{{ catalog_repo_dir }}/{{ catalog_dockerfile }}'"
  docker_image:
    name: "{{ catalog_image_registry }}/{{ catalog_image_namespace }}/{{ catalog_image_name }}"
    build:
      pull: yes
      path: "{{ catalog_repo_dir }}"
      dockerfile: "{{ catalog_repo_dir }}/{{ catalog_dockerfile }}"
      args:
        PERMISSIVE_LOAD: false
    tag: "{{ catalog_image_tag }}"
    push: yes
    source: build
  tags:
    - catalog_build

- name: "Delete previous catalog deployment (it may fail if not exists)"
  shell: "{{ oc_bin_path }} delete deployment {{ catalog_source_name }} -n {{ catalog_source_namespace }}"
  ignore_errors: yes
  tags:
    - catalog_build

- name: "Create '{{ catalog_source_namespace }}' namespace (it may fail, if already exists)"
  shell: "{{ oc_bin_path }} create namespace {{ catalog_source_namespace }}"
  ignore_errors: yes
  tags:
    - catalog_build

- name: "Deploy catalog image as deployment '{{ catalog_source_name }}' in '{{ catalog_source_namespace }}' namespace"
  shell: "{{ oc_bin_path }} create deployment {{ catalog_source_name }} --image={{ catalog_image_registry }}/{{ catalog_image_namespace }}/{{ catalog_image_name }}:{{ catalog_image_tag }} -n={{ catalog_source_namespace }}"
  tags:
    - catalog_build

# - name: "Copy Dockerfile"
#   template:
#     src: "upstream.Dockerfile"
#     dest: "/tmp/upstream.Dockerfile"

# - name: "Clear old build log"
#   file:
#     path: "/tmp/build.log"
#     state: absent

# - name: "Run catalog build"
#   shell: "docker build --build-arg PERMISSIVE_LOAD=false -f /tmp/upstream.Dockerfile -t operatorhub-catalog:dev {{ catalog_repo_dir }} > /tmp/build.log"
#   register: build_image_output

# #temporary for testing
# - name: "Quay login"
#   shell: "docker login -u=\"{{ quay_namespace }}+test\" -p={{ quay_token }} quay.io"
#   no_log: True

# #temporary for testing
# - name: "Quay tag"
#   shell: "docker tag operatorhub-catalog:dev quay.io/{{ quay_namespace }}/catalog"

# #temporary for testing
# - name: "Quay push"
#   shell: "docker push quay.io/{{ quay_namespace }}/catalog"
