---
- name: "Git clone community operators"
  git:
    repo: 'https://github.com/operator-framework/community-operators.git'
    dest: "{{ catalog_repo_dir }}"
    version: master
    force: true

- name: "Copy Dockerfile"
  template:
    src: "upstream.Dockerfile"
    dest: "/tmp/upstream.Dockerfile"

- name: "Clear old build log"
  file:
    path: "/tmp/build.log"
    state: absent

- name: "Run catalog build"
  shell: "docker build --no-cache --build-arg PERMISSIVE_LOAD=false -f /tmp/upstream.Dockerfile -t operatorhub-catalog:dev {{ catalog_repo_dir }} > /tmp/build.log"
  register: build_image_output

#TODO: use Quay pw as an environment secret
- name: "Quay login"
  shell: "docker login -u='op-test+test' -p={{ quay_robot_pw }} quay.io"

- name: "Quay tag"
  shell: "docker tag operatorhub-catalog:dev quay.io/op-test/catalog"

- name: "Quay push"
  shell: "docker push quay.io/op-test/catalog"
