dist: bionic
language: python
os: linux
sudo: required

#TODO:uncomment
#if: branch = master

python:
- "3.8"

env:
- DISTRO_TYPE=upstream KIND_VER=v0.8.1 KUBE_VER=v1.18.2 OLM_VER=0.14.1 SDK_VER=v0.16.0 PLAYBOOK_CMD="ansible-playbook -i localhost, local.yml -e ansible_connection=local -e run_upstream=true -e run_remove_catalog_repo=false -e catalog_repo_dir=$(pwd)"

services:
  - docker

install:
  - pip install ansible
  # - scripts/ci/upgrade-docker

jobs:
  include:
  - stage: Integration Tests
    before_script:
    - $PLAYBOOK_CMD -e kind_version=$KIND_VER -e kind_kube_ver=$KUBE_VER --tags host_build
    # - kind get kubeconfig --name operator-test > ~/.kube/config
    # - docker version

    script:
    - $PLAYBOOK_CMD -e operator_dir=/tmp/community-operators-for-catalog/upstream-community-operators/aqua -e operator_version=1.0.2 --tags pure_test
    - $PLAYBOOK_CMD --tags deploy_bundles --skip-tags always -e operators_config=$(pwd)/test/operatos_config.yaml
