dist: bionic
language: python
os: linux
sudo: required

#TODO:uncomment
#if: branch = master

python:
- "3.8"

env:
- DISTRO_TYPE=upstream PLAYBOOK_CMD="ansible-playbook -i localhost, local.yml -e kind_version=v0.8.1 -e kind_kube_ver=v1.18.2 -e olm_ver=0.14.1 -e operator_sdk_version=v0.16.0 -e ansible_connection=local -e run_upstream=true -e run_remove_catalog_repo=false"
#- DISTRO_TYPE=upstream KIND_VER=v0.8.1 KUBE_VER=v1.18.2 OLM_VER=0.14.1 SDK_VER=v0.16.0 PLAYBOOK_CMD="ansible-playbook -i localhost, local.yml -e ansible_connection=local -e run_upstream=true -e run_remove_catalog_repo=false"

services:
  - docker

install:
  - pip install ansible jmespath
  - $PLAYBOOK_CMD --tags host_build
  # - scripts/ci/upgrade-docker

jobs:
  include:
  - stage: Operator Tests
    name: Testing operator
    script: $PLAYBOOK_CMD -e operator_dir=/tmp/community-operators-for-catalog/upstream-community-operators/aqua -e operator_version=1.0.2 --tags pure_test
  - script: $PLAYBOOK_CMD --tags deploy_bundles --skip-tags always -e operators_config=test/operatos_config.yaml
    name: Deploying of multiple operators to bundle index
  - stage: Operator Index Deploy Tests
    name: Deploying of multiple operators to bundle index
    script:
    - $PLAYBOOK_CMD --tags deploy_bundles --skip-tags always -e operators_config=test/operatos_config.yaml
