dist: bionic
language: python
os: linux
sudo: required

if: type = pull_request

python:
- "3.8"

env:
- DISTRO_TYPE=upstream PLAYBOOK_CMD="ansible-playbook -i localhost, local.yml -e kind_version=v0.8.1 -e kind_kube_ver=v1.18.2 -e olm_ver=0.14.1 -e operator_sdk_version=v0.16.0 -e ansible_connection=local -e run_upstream=true -e run_remove_catalog_repo=false"
#- DISTRO_TYPE=upstream KIND_VER=v0.8.1 KUBE_VER=v1.18.2 OLM_VER=0.14.1 SDK_VER=v0.16.0 PLAYBOOK_CMD="ansible-playbook -i localhost, local.yml -e ansible_connection=local -e run_upstream=true -e run_remove_catalog_repo=false"

services:
  - docker

install:
  - pip install ansible jmespath
  - $PLAYBOOK_CMD --tags host_build
  # - scripts/ci/upgrade-docker

jobs:
  include:
  - stage: Operator Tests pack 1
    name: Testing operator in bundle format
    script: $PLAYBOOK_CMD -e operator_dir=/tmp/community-operators-for-catalog/scripts/bundle-examples/prometheusoperator -e operator_version=0.32.0 --tags pure_test
  - name: 1. Testing operator in manifest format, converting to bundle and bundle test
    script: $PLAYBOOK_CMD -e operator_dir=/tmp/community-operators-for-catalog/upstream-community-operators/aqua -e operator_version=1.0.2 --tags pure_test

    # only 2 at once due to timeout during some prerequisite download
  - stage: Operator Tests pack 2
    name: 2. Testing operator in manifest format, converting to bundle and bundle test
    script: $PLAYBOOK_CMD -e operator_dir=/tmp/community-operators-for-catalog/upstream-community-operators/eclipse-che -e operator_version=7.14.2 -e operator_channel_force=stable --tags pure_test
  - name: 3. Testing operator in manifest format, converting to bundle and bundle test
    script: $PLAYBOOK_CMD -e operator_dir=/tmp/community-operators-for-catalog/upstream-community-operators/jaeger -e operator_version=1.18.0 --tags pure_test

  - stage: Operator Tests from image input (internal purposes only)
    name: Testing operator in image format
    script: $PLAYBOOK_CMD -e operator_input_image=quay.io/cvpops/test-bundle:tigera-131 --tags pure_test

  - stage: Operator Tests to deploy operators to index
    name: Deploying of multiple operators to bundle index test
    script: $PLAYBOOK_CMD --tags deploy_bundles --skip-tags always -e operators_config=test/operatos_config.yaml -e operator_channel_force=stable


