dist: bionic
language: python
os: linux
sudo: required

if: type = pull_request

python:
- "3.8"

services:
  - docker

install:
  - pip install ansible jmespath
  - $ANSIBLE_PLAYBOOK_CMD --tags host_build

jobs:
  include:
  - stage: Operator Tests pack 1
    name: Testing operator in bundle format
    script: $ANSIBLE_PLAYBOOK_CMD -e operator_dir=/tmp/community-operators-for-catalog/scripts/bundle-examples/prometheus -e operator_version=0.32.0 --tags pure_test
  - name: 1. Testing operator in manifest format, converting to bundle and bundle test
    script: $ANSIBLE_PLAYBOOK_CMD -e operator_dir=/tmp/community-operators-for-catalog/upstream-community-operators/aqua -e operator_version=1.0.2 --tags pure_test

  - name: 2. Testing operator in manifest format, converting to bundle and bundle test
    script: $ANSIBLE_PLAYBOOK_CMD -e operator_dir=/tmp/community-operators-for-catalog/upstream-community-operators/eclipse-che -e operator_version=7.14.2 -e operator_channel_force=stable --tags pure_test
  - name: 3. Testing operator in manifest format, converting to bundle and bundle test
    script: $ANSIBLE_PLAYBOOK_CMD -e operator_dir=/tmp/community-operators-for-catalog/upstream-community-operators/jaeger -e operator_version=1.18.0 --tags pure_test
  - name: 4. Testing operator in manifest format and manifest test only (Without conversion to bundle )
    script: $ANSIBLE_PLAYBOOK_CMD -e operator_dir=/tmp/community-operators-for-catalog/upstream-community-operators/aqua -e operator_version=1.0.2 --tags pure_test -e run_bundle_test=false -e run_manifest_test=true

  # # - stage: Operator Tests from image input (internal purposes only)
  # - name: Testing operator in image format
  #   script: $ANSIBLE_PLAYBOOK_CMD -e operator_input_image=quay.io/cvpops/test-bundle:tigera-131 --tags pure_test

  - name: Deploying of multiple operators to bundle index test
    script: $ANSIBLE_PLAYBOOK_CMD --tags deploy_bundles -e operators_config=test/operators_config.yaml
  - name: Deploying of multiple operators to bundle index test with checking prod registry first for bundle image. Local catalog index is rebuilded
    script: $ANSIBLE_PLAYBOOK_CMD --tags deploy_bundles -e operators_config=test/operators_config.yaml -e production_registry_namespace="quay.io/operatorhubio" -e index_force_update=true
