---
- name: Test the operator on a OCP 4.0 cluster with OLM
  hosts: all
  become: false
  gather_facts: false

  vars:
    run_prereqs: true
    run_lint: true
    run_catalog_init: true
    run_deploy: true
    run_scorecard: true
    run_imagesource: true
    run_cleanup: true
    scorecard_first_cr: true
    openshift_namespace: "test-operator"
    work_dir: "/tmp/operator-test"
    testing_bin_path: "{{ work_dir }}/bin"
    current_channel: '' # Added to avoid a potential bug with undefined variables

  tasks:
    - set_fact:
        operator_work_dir: "{{ work_dir }}/operator-files"
        olm_operator_files_path: "{{ work_dir }}/olm-operator-files"
        scorecard_cr_dir: "{{ work_dir }}/scorecard-cr-files"
        kube_objects_dir: "{{ work_dir }}/kube_objects"
        testing_bin_path: "{{ work_dir }}/bin"
        oc_bin_path: "{{ testing_bin_path }}/oc"
        jq_bin_path: "{{ testing_bin_path }}/jq"
        yq_bin_path: "{{ testing_bin_path }}/yq"
        go_bin_path: "{{ testing_bin_path }}/go/bin/go"
        operator_sdk_bin_path: "{{ testing_bin_path }}/operator-sdk"
        offline_cataloger_bin_path: "offline-cataloger"

    - name: "Clear the operator working directory"
      file:
        path: "{{ operator_work_dir }}"
        state: absent

    - name: "Clear the scorecard CR directory"
      file:
        path: "{{ scorecard_cr_dir }}"
        state: absent
      when: run_scorecard|bool

    - name: "Create the scorecard CR directory"
      file:
        path: "{{ scorecard_cr_dir }}"
        state: directory
      when: run_scorecard|bool

    - name: "Install operator testing prerequisites"
      include_role:
        name: install_operator_prereqs
      when: run_prereqs|bool

    - name: "Build upstream catalog"
      include_role:
        name: build_upstream_catalog
        #when distro_type == "upstream"