---
- name: Test the operator on a OCP 4.0 cluster with OLM
  hosts: all
  become: false
  gather_facts: false

  vars:
    run_prereqs: true
    run_lint: true
    run_catalog_init: true
    run_deploy: true
    run_scorecard: true
    run_imagesource: true
    run_cleanup: true
    scorecard_first_cr: true
    openshift_namespace: "test-operator"
    work_dir: "/tmp/operator-test"
    testing_bin_path: "{{ work_dir }}/bin"
    current_channel: '' # Added to avoid a potential bug with undefined variables
    distro_type: "{{ DISTRO_TYPE | default('') }}"

  tasks:
    - set_fact:
        distro_type: "{{ DISTRO_TYPE | default('') }}"
        operator_work_dir: "{{ work_dir }}/operator-files"
        olm_operator_files_path: "{{ work_dir }}/olm-operator-files"
        scorecard_cr_dir: "{{ work_dir }}/scorecard-cr-files"
        kube_objects_dir: "{{ work_dir }}/kube_objects"
        testing_bin_path: "{{ work_dir }}/bin"
        oc_bin_path: "{{ '/snap/bin/kubectl' if (distro_type == 'upstream') else \"{{ testing_bin_path }}/oc\" }}"
        jq_bin_path: "{{ testing_bin_path }}/jq"
        yq_bin_path: "{{ testing_bin_path }}/yq"
        go_bin_path: "{{ testing_bin_path }}/go/bin/go"
        operator_sdk_bin_path: "{{ testing_bin_path }}/operator-sdk"
        offline_cataloger_bin_path: "offline-cataloger"
        KIND_ver: "{{ KIND_VER | default('') }}"
        KIND_bin_path: "{{ testing_bin_path }}/kind"
        KIND_kube_ver: "{{ KIND_KUBE_VER | default('') }}"
        olm_ver: "{{ OLM_VER | default('') }}"



    - name: "catalog"
      include_role:
        name: upstream_registry
      when: distro_type == "upstream"
