---
- name: Test
  hosts: all
  become: false
  gather_facts: false

  vars:
    run_upstream: true
    distro_type: "{{ 'upstream' if run_upstream else '' }}"

  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
    when: run_upstream|bool

  pre_tasks:
    - setup:
      tags:
        - always
      when: run_upstream|bool

  roles:
    - { role: install_base_packages, tags: ["base"] }
    - { role: install_docker, tags: ["docker"] }
    - { role: install_kubectl, tags: ["kubectl"] }
    - { role: install_kind, tags: ["kind"] }
    - { role: install_operator_prereqs, tags: ["operator_prereqs"] }
    - { role: build_upstream_catalog, tags: ["operator_catalog"] }
    # - { role: operator_courier_verify, tags: ["pure_test", "operator_courier_verify"] }
