---
- name: "Deploy the operator bundle"
  hosts: all
  become: false
  gather_facts: false

  vars:
    run_upstream: false
    work_dir: "/tmp/operator-test"
    testing_bin_path: "{{ work_dir }}/bin"
    operators_for_index: []
    opm_container_tool: "docker"

  tasks:
    - name: "Setting basic variables for deploy tasks"
      set_fact:
        operator_work_dir: "{{ work_dir }}/operator-files"
        operator_bundle_dir: "{{ work_dir }}/operator-bundle"
        jq_bin_path: "{{ testing_bin_path }}/jq"
        yq_bin_path: "{{ testing_bin_path }}/yq"
        umoci_bin_path: "{{ testing_bin_path }}/umoci"
        opm_bin_path: "{{ testing_bin_path }}/opm"
        operator_sdk_bin_path: "{{ testing_bin_path }}/operator-sdk"
        oc_bin_path: '{{ ''kubectl'' if run_upstream else "{{ testing_bin_path }}/oc" }}'

    - name: "Quay login"
      shell: "{{ opm_container_tool }} login -u=\"{{ quay_user }}\" -p={{ quay_password }} quay.io"
      no_log: True
      when:
        - quay_user is defined
        - quay_password is defined
        - quay_user != ""
        - quay_password != ""

    - name: "Handle operators input file"
      block:
        - name: "Parsing config file '{{ operators_config }}'"
          include_vars:
            file: "{{ operators_config }}"
            name: operators_config_vars

        - name: "Set facts from config variables"
          set_fact:
            operators: "{{ operators_config_vars.operators | default([])}}"
            operator_base_dir: "{{ operators_config_vars.operator_base_dir | default('') }}"

        - name: "Failing when 'operator base dir' is not found in '{{ operators_config }}'"
          fail:
            msg: "'operator_base_dir' was not found in config file '{{ operators_config }}' !!!"
          when: operator_base_dir == ""

        - name: "Checking if operator base dir exists"
          stat:
            path: "{{ operator_base_dir }}"
          register: operator_base_dir_st

        - name: "Failing when operator base dir doesn't exists"
          fail:
            msg: "Operator base dir '{{ operator_base_dir }}' was not found !!!"
          when: not operator_base_dir_st.stat.exists

        - name: "Failing when 'operator_base_dir' is not defined or is empty"
          fail:
            msg: "The 'operator_base_dir' is not defined or is empty"
          when: operator_base_dir == ""
      when: operators_config is defined

    - name: "Set operator name to list from operator name"
      set_fact:
        operators: '["{{ operator_dir | basename }}"]'
      when:
        - operator_dir is defined
        - operators is undefined
        - operators_config is undefined

    - name: "Setting 'operators_for_index' variable"
      set_fact:
        operators_for_index: "{{ operators_for_index }}"

    - name: "Deploy operators bundle images"
      include_role:
        name:
          build_operator_bundle
      vars:
        operator_dir: "{{ operator_base_dir }}/{{ op_item }}"
      loop: "{{ operators }}"
      loop_control:
        loop_var: op_item
      when:
        - run_upstream|bool

    - name: "Deploy operators to index"
      include_role:
        name:
          build_operators_index
      when:
        - run_upstream|bool