---
- name: Test
  hosts: all
  become: false
  gather_facts: false

  vars:
    run_prereqs: true
    run_lint: true
    run_catalog_init: true
    run_deploy: true
    run_scorecard: true
    run_imagesource: true
    run_cleanup: true
    scorecard_first_cr: true
    openshift_namespace: "test-operator"
    work_dir: "/tmp/operator-test"
    testing_bin_path: "{{ work_dir }}/bin"
    current_channel: '' # Added to avoid a potential bug with undefined variables
    distro_type: "{{ DISTRO_TYPE | default('') }}"

  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"

  pre_tasks:
    - setup:
      tags: 
      - always
    - set_fact:
        distro_type: "{{ DISTRO_TYPE | default('') }}"
        operator_work_dir: "{{ work_dir }}/operator-files"
        olm_operator_files_path: "{{ work_dir }}/olm-operator-files"
        scorecard_cr_dir: "{{ work_dir }}/scorecard-cr-files"
        kube_objects_dir: "{{ work_dir }}/kube_objects"
        testing_bin_path: "{{ work_dir }}/bin"
        oc_bin_path: "{{ 'kubectl' if (distro_type == 'upstream') else \"{{ testing_bin_path }}/oc\" }}"
        jq_bin_path: "{{ testing_bin_path }}/jq"
        yq_bin_path: "{{ testing_bin_path }}/yq"
        go_bin_path: "{{ testing_bin_path }}/go/bin/go"
        operator_sdk_bin_path: "{{ testing_bin_path }}/operator-sdk"
        offline_cataloger_bin_path: "offline-cataloger"
        kind_ver: "{{ KIND_VER | default('') }}"
        # KIND_bin_path: "{{ testing_bin_path }}/kind"
        # KIND_kube_ver: "{{ KIND_KUBE_VER | default('') }}"
        kind_bin_path: "{{ testing_bin_path }}/kind"
        kind_kube_ver: "{{ KIND_KUBE_VER | default('latest') }}" # mvala
        olm_ver: "{{ OLM_VER | default('') }}"
      tags: always

  roles:
    - { role: install_base_packages, tags: ["base"] }
    - { role: docker, tags: ["docker"] }
    - { role: kubectl, tags: ["kubectl"] }
    - { role: kind, tags: ["kind"] }
    - { role: install_operator_prereqs, tags: ["operator_prereqs"] }
    - { role: todo, tags: ["pure_test"]}
    # - { role: operator_courier_verify, tags: ["pure_test", "operator_courier_verify"] }
    
  tasks:
  
    - name: debug
      debug:
        msg: "user : {{ ansible_user_id }}"
        verbosity: 2
      tags:
        always
