---
- name: "Sanity check of index image"
  block:
    - debug:
        var: bundle_index_image

    - name: "Stop previous index container '{{ sanity_check_container_name }}''"
      shell: "{{ opm_container_tool }} rm -f {{ sanity_check_container_name }}"
      failed_when: false
      changed_when: false

    - name: "Start index container {{ bundle_index_image }}"
      shell: "{{ opm_container_tool }} run -d --name {{ sanity_check_container_name }} {{ bundle_index_image }}"

    - name: "Remove db filename '{{ sqlite_db_file }}'"
      file:
        path: "{{ sqlite_db_file }}"
        state: absent

    - name: "Extract db file to '{{ sqlite_db_file }}'"
      shell: "{{ opm_container_tool }} cp {{ sanity_check_container_name }}:/database/index.db {{ sqlite_db_file }}"

    - name: "Print packages"
      shell: "{{ sqlite_tool }} {{ sqlite_db_file }} 'select name from package' | sed 's/^\ | $//g'| paste -sd, -"

    - name: "Stop index container '{{ sanity_check_container_name }}'"
      shell: "{{ opm_container_tool }} rm -f {{ sanity_check_container_name }}"
  tags:
    - mirror_index
    - deploy_bundles
    - index_check
  when:
    - bundle_index_image is defined
    - bundle_index_image != ""


