---
- name: "Sanity check of index image"
  block:
    - debug:
        var: bundle_index_image

    - name: "Stop previous index container '{{ sanity_check_container_name }}''"
      shell: "{{ opm_container_tool }} rm -f {{ sanity_check_container_name }}"
      failed_when: false
      changed_when: false
      no_log: true

    - name: "Start index container {{ bundle_index_image }}"
      shell: "{{ opm_container_tool }} run -d --name {{ sanity_check_container_name }} {{ bundle_index_image }}"

    - name: "Remove db filename '{{ sqlite_db_file }}'"
      file:
        path: "{{ sqlite_db_file }}"
        state: absent

    - name: "Extract db file to '{{ sqlite_db_file }}'"
      shell: "{{ opm_container_tool }} cp {{ sanity_check_container_name }}:/database/index.db {{ sqlite_db_file }}"

    - name: "Print list of packages"
      shell: "{{ sqlite_tool }} {{ sqlite_db_file }} 'select bundlepath from operatorbundle' | sed 's/^\ | $//g'| cut -sd / -f 3- | paste -sd, -"
      register: chi_index_operators_out
      no_log: true

    - name: "Stop index container '{{ sanity_check_container_name }}'"
      shell: "{{ opm_container_tool }} rm -f {{ sanity_check_container_name }}"

    - name: "Find all directories in git repo"
      shell:
        cmd: "find . -type d -mindepth 2 -maxdepth 2 | cut -sd / -f 2- | sort"
        chdir: "{{ operator_base_dir }}"
      register: chi_git_operators_out
      no_log: true

    - name: "Set list of all operators in index"
      set_fact:
        chi_index_operators: "{{ chi_index_operators_out.stdout.split(',') }}"

    - pause:

    - name: "Set list of all operators in git repo"
      set_fact:
        chi_git_operators: "{{ (chi_git_operators_out.stdout | replace('/',':v') ).split() }}"

    - name: "Setting list of operators present in index, but not in git"
      set_fact:
        chi_index_not_git_operators: "{{ chi_index_operators | difference(chi_git_operators) }}"
      no_log: true

    - name: "Setting list of operators present in git, but not in index"
      set_fact:
        chi_git_not_index_operators: "{{ chi_git_operators | difference(chi_index_operators) }}"
      no_log: true

    - name: "Setting list of missing operators"
      set_fact:
        chi_missing_operators: "{{ chi_git_not_index_operators | union(chi_index_not_git_operators) }}"
      no_log: true

    - name: "Setting list of uncomplete packages"
      set_fact:
        chi_uncomplete_packages_list: "{{ chi_missing_operators | replace(':v','/') }}"

    - set_fact:
        chi_uncomplete_packages: []

    - set_fact:
        chi_uncomplete_packages: "{{ chi_uncomplete_packages }} + [ '{{ item | dirname }}' ]"
      with_items: "{{ chi_uncomplete_packages_list }}"
  tags:
    - mirror_index
    - deploy_bundles
    - index_check
  when:
    - bundle_index_image is defined
    - bundle_index_image != ""
