---
- name: "Sanity check of index image"
  block:
    - debug:
        var: bundle_index_image

    - name: "Stop previous index container '{{ sanity_check_container_name }}''"
      shell: "{{ opm_container_tool }} rm -f {{ sanity_check_container_name }}"
      failed_when: false
      changed_when: false

    - name: "Start index container {{ bundle_index_image }}"
      shell: "{{ opm_container_tool }} run -d --name {{ sanity_check_container_name }} {{ bundle_index_image }}"

    - name: "Remove db filename '{{ sqlite_db_file }}'"
      file:
        path: "{{ sqlite_db_file }}"
        state: absent

    - name: "Extract db file to '{{ sqlite_db_file }}'"
      shell: "{{ opm_container_tool }} cp {{ sanity_check_container_name }}:/database/index.db {{ sqlite_db_file }}"

    - name: "Print list of packages"
      # shell: "{{ sqlite_tool }} {{ sqlite_db_file }} 'select name from package' | sed 's/^\ | $//g'| paste -sd, -"
      shell: "{{ sqlite_tool }} {{ sqlite_db_file }} 'select bundlepath from operatorbundle' | sed 's/^\ | $//g'| paste -sd, -"
      register: chi_index_operators_out


    - name: "Find all directories in git repo"
      shell:
        cmd: "find . -type d -mindepth 2 -maxdepth 2 | cut -sd / -f 2- | sort"
        chdir: "{{ operator_base_dir }}"
      register: chi_git_operators_out

    - name: "Set list of all operators in index"
      set_fact:
        chi_index_operators: "{{ (chi_index_operators_out.stdout| replace('quay.io/operatorhubio/','')).split(',') }}"

    - name: "Set list of all operators in git repo"
      set_fact:
        chi_git_operators: "{{ (chi_git_operators_out.stdout | replace('/',':v') ).split() }}"

    - name: "XXX debug"
      debug:
        var: chi_index_operators| length
    - name: "XXX debug"
      debug:
        var: chi_git_operators| length

    - name:
      set_fact:
        xxx: "{{ chi_index_operators | difference(chi_git_operators) }}"
    - name: "XXX debug"
      debug:
        var: xxx

    - name:
      set_fact:
        xxx2: "{{ chi_git_operators | difference(chi_index_operators) }}"
    - name: "XXX debug"
      debug:
        var: xxx2



    - name: "Stop index container '{{ sanity_check_container_name }}'"
      shell: "{{ opm_container_tool }} rm -f {{ sanity_check_container_name }}"
  tags:
    - mirror_index
    - deploy_bundles
    - index_check
  when:
    - bundle_index_image is defined
    - bundle_index_image != ""


