---
- set_fact:
    final_list: []

- name: "Set operator name - checking {{ item.name }}"
  set_fact:
    dov_op_name: "{{ item.name }}"

- name: "Pass operator versions to loop"
  set_fact:
    versions_processing: "{{ item.versions }}"

- name: "Loop over all operator versions"
  include_tasks: op_ver.yml
  loop: "{{ versions_processing }}"

- name: "Adding version"
  set_fact:
   dov_operators_op_ver: "{{ dov_operators_op_ver | default([]) | union( [{'name': dov_op_name, 'versions': final_list }]) }}"

- debug:
    var: dov_operators_op_ver