---
- name: "Kind delete old catalog cluster"
  shell: "{{ KIND_bin_path }} delete cluster --name kind"
  become: yes
  ignore_errors: true

- name: "Copy registry startup script"
  template:
    src: "kind_registry.sh"
    dest: "/tmp/kind_registry.sh"

- name: "chmod"
  file:
    path: "/tmp/kind_registry.sh"
    mode: +x

- name: "Run script to create catalog machine"
  shell: "/tmp/kind_registry.sh"
  become: yes

- name: "Docker tag"
  shell: "docker tag operatorhub-catalog:dev localhost:5000/catalog"

- name: "Docker push to registry"
  shell: "docker push localhost:5000/catalog"

- name: "Starting catalog"
  shell: "kubectl create deployment hello-server --image=localhost:5000/hello-app:1.0"