- set_fact:
    bundle_image: "{{ bundle_registry }}/{{ bundle_image_namespace }}/{{ bundle_add_name }}:v{{ bundle_add_ver }}"

- name: Retag bundle input image
  block:
    - name: Retag image to {{ bundle_image }}
      shell: "{{ opm_container_tool }} tag {{ operator_input_image  }} {{ bundle_image }}"
    - name: Push image {{ bundle_image }}
      shell: "{{ opm_container_tool }} push {{ bundle_image }}"
  when: operator_input_image != ""

- debug:
    var: bundle_image

- name: Build index image {{ bundle_index_image }}
  shell: "{{ opm_bin_path }} index add -d {{ bundle_db }} -u {{ opm_container_tool }} --bundles {{ bundle_image }} --tag {{ bundle_index_image }} --skip-tls"