---
- set_fact:
    bundle_index_image: "{{ bundle_index_registry }}/{{ bundle_index_image_namespace }}/{{ bundle_index_image_name }}:{{ bundle_index_image_version }}"

- name: Remove index image {{ bundle_index_image }}
  shell: "{{ opm_container_tool }} rmi -f {{ bundle_index_image }}"

- debug:
    var: ba_versions

- name: Add all bundle images to index
  include_tasks: bundle_add.yml
  vars:
    bundle_add_name: "{{ ba_name }}"
  loop: "{{ ba_versions }}"
  loop_control:
    loop_var: bundle_add_ver

- name: Push bundle image {{ bundle_index_image }}
  shell: "{{ opm_container_tool }} push {{ bundle_index_image }}"
