---
- debug:
    var: bar_op

- debug:
    var: app_registry_base_dir

- name: "Setting export directory"
  set_fact:
    bar_operator_package_name: "{{ bar_op | basename }}"
    bar_download_folder: "{{ app_registry_base_dir }}/{{ bar_op | basename }}"

- name: "Ensure that the 'bar_download_folder' directory exists and is empty"
  file:
    state: "{{ item }}"
    path: "{{ bar_download_folder }}"
  with_items:
    - absent
    - directory

- name: "Trying to export operator '{{ bar_operator_package_name }}' from index image {{ bundle_index_image }}"
  shell: "{{ opm_bin_path }} index export -c {{ opm_container_tool }} --package {{ bar_operator_package_name }} --index {{ bundle_index_image }} --download-folder {{ bar_download_folder }}"
  register: bar_export_rc
