---

- name: "Uninstall kind binary"
  file:
    path: "{{ kind_bin_path }}"
    state: absent
  become: yes
  tags:
    - never
    - uninstall

- name: "Ensure kind binary is installed"
  block:
    - name: "Check that the kind executable exists"
      stat:
        path: "{{ kind_bin_path }}"
      register: rc_kind

    - name: "Install kind binary"
      get_url:
        url: "https://github.com/kubernetes-sigs/kind/releases/download/{{ kind_version }}/kind-linux-amd64"
        dest: "{{ kind_bin_path }}"
        mode: '0755'
      register: kind_install_result
      until: kind_install_result.status_code is undefined or kind_install_result.status_code == 200
      retries: 10
      delay: 15
      failed_when: kind_install_result is failure
      become: yes
      when: rc_kind.stat.exists == false
  tags:
    - install
    - host_build

- name: "Reset Kind with registry"
  include_role:
    name: reset_kind
  tags:
    - reset
    - install
    - host_build
