---
- block:
    - name: "Searching for cvs file"
      find:
        paths: "{{ operator_dir }}/{{ operator_version }}"
        recurse: yes
        file_type: file
      register: dc_all_operator_files
#    - set_fact:
#        dc_all_operator_files_paths: "{{ dc_all_operator_files[].path }}"

    - name: "Prepare list of operator files"
      set_fact:
       dc_all_operator_files_paths: "{{ dc_all_operator_files_paths | default([]) + [item.path] }}"
      with_items: "{{ dc_all_operator_files.files }}"

    - name: "Filter csv out"
      set_fact:
#       dc_operator_files_paths_without_csv: "{{csv_file_path|list}} not in {{ dc_all_operator_files_paths }}"
       dc_operator_files_paths_without_csv: "{{ dc_all_operator_files_paths | reject('in', csv_file_path) }}"

    - name: "Detect CRD changes"
      include_tasks: detect_edit.yml

    - name: "Parse"
      set_fact:
        dc_file_end: "{{ csv_file_path.split('community-operators-for-catalog/')[-1] }}"
        dc_csv_pkg_format_found: false
        dc_csv_current_format_found: false
        dc_diff_result:
        dc_diff_keys_result:

    - name: "Target file"
      set_fact:
        dc_master_file_path: "https://raw.githubusercontent.com/operator-framework/community-operators/master/{{ dc_file_end }}"

    - name: "Check if CSV file is present on master"
      uri:
        url: "{{ dc_master_file_path }}"
    #    url:  https://raw.githubusercontent.com/operator-framework/community-operators/master/community-operators/flux/0.5.1/manifests/flux.v0.5.1.clusterser
        timeout: 1
        return_content: yes
      register: dc_master_file
      changed_when: no
      check_mode: no
      failed_when: no

    - name: "Mark file as found"
      set_fact:
        dc_csv_current_format_found: true
      when: not dc_master_file.content.startswith("404")

    - name: "Check in package manifest format"
      block:
        - name: "Path according package manifest format"
          set_fact:
            dc_master_file_path: "{{ dc_file_end | replace('manifests/','')}}"
#TODO:^
        - debug:
            var: dc_master_file_path

        - name: "Set dc_master_file_path"
          set_fact:
            dc_master_file_path: "https://raw.githubusercontent.com/operator-framework/community-operators/master/{{ dc_file_end }}"

        - name: "Check if file is present on master"
          uri:
            url: "{{ dc_master_file_path }}"
            timeout: 1
            return_content: yes
          register: dc_master_pkg_format
          changed_when: no
          check_mode: no
          failed_when: no

        - name: "Set 'true' that file was found in an old format on the master"
          set_fact:
            dc_pkg_format_found: true
          when: not dc_master_pkg_format.content.startswith("404")

      when:
        - not dc_current_format_found|bool
        - 'manifest' in dc_master_file_path

    - debug:
        var: dc_master_file

    - name: "CSV found on Git"
      block:
        - name: "Detect diff with dyff"
          shell: 'dyff between -b -l {{ dc_master_file_path }} {{ item }}'
          register: dc_diff_result
          environment:
            PATH: "/tmp/operator-test/bin:{{ ansible_env.PATH }}"

        - debug:
            var: dc_diff_result.stdout
        - debug:
            var: dc_diff_result.stdout|length

        - name: "Diff found"
          block:

          - name: "Status in case of bigger change"
            fail:
              msg: "File {{ dc_file_end }} edited. Consider bumping your operator version. In exceptional cases, it could be overridden by setting 'allow/serious-changes-to-existing' label"
            when:
              - dc_diff_result.stdout|length>0

          when:
            - dc_diff_result.stdout is defined
            - dc_diff_result.stdout|length>1

        - name: "Status in case of no difference"
          debug:
            msg: "No files difference against master (csv excluded) [OK]"
          when:
            - dc_diff_result.stdout|length<2
      when: (dc_current_format_found|bool) or (dc_pkg_format_found|bool)

    - name: "Status in case of no file to compare"
      debug:
        msg: "No file for comparison on master [OK]"
      when:
        - not dc_current_format_found|bool
        - not dc_pkg_format_found|bool
  tags:
    - cosmetics