---

- name: "Install required system packages"
  package: 
    name:
      - curl
      - ca-certificates
      - python3-pip
      - python3-setuptools
      - docker-py
    state: latest 
    update_cache: yes
  become: yes
  tags:
    - install
    - image_build

- name: "Install required for Ubuntu system only"
  package: 
    name:
      - software-properties-common
      - virtualenv
      - python-docker
    state: latest 
    update_cache: yes
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - install
    - image_build

- name: "Install required for RedHat/CentOS system only"
  package: 
    name:
      - python3-virtualenv
      - python3-dockerpty
    state: latest 
    update_cache: yes
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags:
      - install
      - image_build