- set_fact:
    bundle_index_image: "{{ bundle_registry }}/{{ bundle_index_image_namespace }}/{{ bundle_index_image_name }}:{{ bundle_index_image_version }}"

- name: Remove index image {{ bundle_index_image }}
  shell: "{{ opm_container_tool }} rmi -f {{ bundle_index_image }}"

- debug:
    var: operators_for_index

- name: "Build index image for all operators"
  include_role:
    name: build_operator_index
  vars:
    ba_name: "{{ ops_item.name }}"
    ba_versions: "{{ ops_item.versions }}"
  loop: "{{ operators_for_index }}"
  loop_control:
    loop_var: ops_item

- name: Push bundle image {{ bundle_index_image }}
  shell: "{{ opm_container_tool }} push {{ bundle_index_image }}"
  when: operators_for_index[0] is defined
