---
- name: "Mirroring image to multiple locations"
  block:
    - name: "Parsing output image with login information"
      set_fact:
        ms_info: "{{ mi_item.split('|') }}"

    - name: "Failing when image is not defined"
      fail:
        msg: "Mirror image is not defined correctly !!! Input: '{{ mi_item }}'"
      when:
        - ms_info.0 is undefined

    - name: "Login to docker registry"
      shell: "{{ opm_container_tool }} login -u={{ ms_info[1]}} -p={{ ms_info[2] }} {{  ms_info[0].split('/')[0] }}"
      # no_log: True
      when:
        - ms_info.1 is defined
        - ms_info.2 is defined

    - name: "Mirroring index image '{{ mirror_input_image }}' to mirror location '{{ ms_info[0] }}'"
      block:
        - name: "Doing retag of '{{ mirror_input_image }}' to '{{ ms_info[0] }}'"
          shell: "{{ opm_container_tool }} tag {{ mirror_input_image  }} {{ ms_info[0] }}"
        - name: "Push image '{{ ms_info[0] }}'"
          shell: "{{ opm_container_tool }} push {{ ms_info[0] }}"
      when:
        - mirror_input_image is defined
        - mirror_input_image != ""
  tags:
    - mirror_index
    - deploy_bundles
