work_dir: /tmp/operator-test
catalog_repo_dir: /tmp/community-operators-for-catalog
operator_work_dir: /tmp/operator-test/operator-files
operator_sdk_bin_path: operator-sdk
check_validation_result: true
