- debug: var=operators_index

- name: "Build bundle index image"
  include_role:
    name: build_index_bundle
  vars:
    ba_name: "{{ ops_item.name }}"
    ba_versions: "{{ ops_item.versions }}"
  loop: "{{ operators_index }}"
  loop_control:
    loop_var: ops_item
